module Utilities
  MAC_DEFAULT_APPS = [
    "App Store.app",
    "Automator.app",
    "Calculator.app",
    "Calendar.app",
    "Chess.app",
    "Contacts.app",
    "Dashboard.app",
    "Dictionary.app",
    "DVD Player.app",
    "FaceTime.app",
    "Font Book.app",
    "Game Center.app",
    "iBooks.app",
    "Image Capture.app",
    "iTunes.app",
    "Launchpad.app",
    "Mail.app",
    "Maps.app",
    "Messages.app",
    "Mission Control.app",
    "Notes.app",
    "Photo Booth.app",
    "Photos.app",
    "Preview.app",
    "QuickTime Player.app",
    "Reminders.app",
    "Safari.app",
    "Stickies.app",
    "System Preferences.app",
    "TextEdit.app",
    "Time Machine.app"
  ]
end
